### ISSUE TITLE
Investigate using on mobile 

### ISSUE THREAD

**Issue by zaboco** [zaboco/elm-draggable#25]
- events for `touch`
- see if Subs `Mouse.moves`, `.ups` works for touch

**Comment by abingham** [comment]
What's the status of this? I've used elm-draggable on a project, and the client is interested in supporting drag on mobile. Is this just a question of finding time to do it, or is there some research needed to figure out how to do it?

**Comment by zaboco** [comment]
This is an issue that I've added after feedback got from the slack group, I left it here as a reminder, but didn't really take the time to investigate further. Right now I'm on vacation (including elm-europe 🇫🇷  🙂 ), so I won't have time to look into it, but I saw that there is [this touch events package](http://package.elm-lang.org/packages/mpizenberg/elm-touch-events/latest), and if you want, you can try to integrate it in this library and see how it goes.

Ideally, it should be as easy as adding the touch events to [the subscriptions](https://github.com/zaboco/elm-draggable/blob/master/src/Draggable.elm#L113) and a `touchTrigger` similar to [`mouseTrigger`](https://github.com/zaboco/elm-draggable/blob/master/src/Draggable.elm#L123). But I don't know if this works out of the box.

If you don't have the time, I'll try this after maybe 2 weeks from now.

**Comment by abingham** [comment]
That sounds promising. I'll see if I can find some time to integrate the touch package. I won't be at Elm Europe this year, but I'm speaking at Oslo Elm Day soon...there's a lot of activity in the Elm world now!

**Comment by abingham** [comment]
Take a look at [my `add-touch-support` branch](https://github.com/abingham/elm-draggable/tree/add-touch-support). I *think* this does the right thing, but I'm not entirely confident in it. 

I've tested it using "BasicExample.elm" in the mobile emulator in Firefox, and it indeed responds to touch events as I expect. If I add `touchTriggers` to the draggable then I can move it around in the emulator. If I remove `touchTriggers` then I can't.

Anyhow, have a look at let me know what you think. If you'd prefer a PR (i.e. so you can use github's review tools), I'll be happy to create one.

**Comment by zaboco** [comment]
Hi @abingham, thanks for looking into that. Indeed, it looks right. I'll test it myself with more use-cases these days and then it will be good to merge. 

And yes, a PR is the best way to go. In the mean time, a little documentation would also help, if you're willing to write it. If not, it's fine, I can write it. Thanks again!

**Comment by zaboco** [comment]
published in [3.1.0](http://package.elm-lang.org/packages/zaboco/elm-draggable/3.1.0)
