### ISSUE TITLE
Additional information about the events

### ISSUE THREAD

**Issue by ggazzi** [zaboco/elm-draggable#32]
When working on a complex use case, I needed more information about the dragStart and click events. I'm writing an [editor for directed graphs](https://github.com/ggazzi/category-diagram-editor), which requires handling clicks and drags differently if the shift key was pressed, as well as obtaining the position where a click was made (relative to a parent SVG element).

I'm not sure if this sort of use case is the goal of this library, but elm-draggable is at least a very good starting point to implement it. Therefore, in order to implement the editor, I created a [fork of this library](https://github.com/ggazzi/elm-draggable/tree/custom-info) and created an alternative API which allows the caller to pass a custom JSON decoder to `mouseTrigger`, which will use it to extract information from MouseEvents.

While this alternative API may be too complex for simple application, providing something like it alongside the current API might be useful, and shouldn't affect the underlying implementation too much.

**Comment by zaboco** [comment]
I've actually wanted to include the position in the events, but I din't know how to get the relative position inside the clicked element.

Anyway, it is a valid use case, I think it should be part of the API. When I was working on it, I was thinking of adding an extra argument to `onMouseDown`, `onDragStart` and `onClick`. So, for example, the signature of one of them would be:
```elm
onMouseDown: (Key -> Position -> msg) -> Event msg
```

Or maybe group the two in one `Context` record
```elm
type alias Context = { key: Key, position: Position }

onMouseDown: (Context -> msg) -> Event msg
```

What do you thing, would that be ok?

PS. Really like the graph app, it looks very nice 👍

**Comment by ggazzi** [comment]
I actually tried something very similar to your `Context`, but I don't think there's a position that would be useful for many people :disappointed: 

I'm using the `offsetX` and `offsetY` fields of the `MouseEvent`, which seem to work OK in my case. But they work very inconsistently depending on browser and target element. Chromium and Firefox seem to work differently for elements within an SVG tag: Chromium will give the position relative to the container `svg`; Firefox, on the other hand, will give the position relative to the target subelement of `svg`.

I think that, at this point, different applications will need different things from the event. So it would be cool to have an "advanced API" where users can use their own JSON decoders. This would allow some exploration to figure out what belongs in a `Context` record or something similar.

We could also take this discussion to the [elm subreddit](https://www.reddit.com/r/elm/) or to the [elm-dev mailing list](https://groups.google.com/forum/#!msg/elm-dev/oZ3xW_nMPNo/0y8j-N8HCQAJ), if you want more feedback.

PS. Thanks! Couldn't have done it without your library!

**Comment by zaboco** [comment]
@ggazzi I've made a `customMouseTrigger` on #33. Please let me know what you think about the API, is it helpful? It's not ideal, but I've tried to keep the existing API untouched.

**Comment by ggazzi** [comment]
@zaboco Sorry it took me so long to respond, I was on vacation.

The API in #33 is indeed not ideal, but it seems workable. I'll try to use it and see how it goes.

**Comment by ggazzi** [comment]
I've adapted my app for the new API and it works nicely!

Having to store the position of the click/dragstart before it actually happens is a minor pain point, but not a big issue.

**Comment by zaboco** [comment]
Cool, glad that it's fine. I'll publish this as soon as I can. 

I have some ideas of simplifying the API (with breaking changes), I'll make a branch and ask for feedback if you don't mind.
