### ISSUE TITLE
2.1.0 broken mouseTrigger / onDragStart

### ISSUE THREAD

**Issue by turboMaCk** [zaboco/elm-draggable#36]
Hello @zaboco!

Thx for nice package. However I have to report that since upgrade to `2.1.0` this stopped working for me.

The root of the problem is that I always receive empty string in my `DragStart` Msg (set as Msg constructor for `onDragStart` in `customConfig`. I'm using `mouseTrigger` event.

Downgrading back to 2.0.2 solved this issue for me.

Let me know if you need any help with debugging and resolving this. I think I can dig deeper and try to solve this in PR since we are going to use this lib in production.

Cheers!
Marek

**Comment by zaboco** [comment]
Yes, it is actually an issue that was solved in `3.0.0` but I forgot to solve it in `2.*` too. Also, I realize I should add some integration tests to catch issues like this one.

**Comment by turboMaCk** [comment]
Understandable. Stuff like this is pretty hard to test. I think I'll be able to prepare PR to make patch release for 2.x.x happen if you're interested.

Also I'm working on lib that uses this package as lower level abstraction for creating drag and drop sorting - I'll make sure it's upgraded to 3.x.x before I push first release out.

Let me know if you want me to work on that patch. At least something I can contribute back.

Have a nice day!
Marek

**Comment by zaboco** [comment]
It's ok, it was a trivial fix, thanks anyway. It is published as [2.1.1](http://package.elm-lang.org/packages/zaboco/elm-draggable/2.1.1)

**Comment by turboMaCk** [comment]
:+1: Thanks!
