### ISSUE TITLE
Work with Pointer events as well

### ISSUE THREAD

**Issue by simonh1000** [zaboco/elm-draggable#44]
I tried the demos in Chrome using the phone emulation mode. This uses pointer events I think and the result was that nothing was draggable. Any thoughts about supporting this?

**Comment by zaboco** [comment]
It is done in https://github.com/zaboco/elm-draggable/pull/41, it just seems that I've forgot to publish the example on gh-pages after merging the PR 😅. I'll do that these days

**Comment by simonh1000** [comment]
thansk

**Comment by zaboco** [comment]
The examples are updated, you can try [the basic example](https://zaboco.github.io/elm-draggable/basic.html)

**Comment by ta3pks** [comment]
I dont know how your basic example is working for me it does not trigger any model udates and how are you actually creating subscriptions without writing js counterpart which actually send data to the port ?

**Comment by zaboco** [comment]
Hi @NikosEfthias. I tried and it still works for me, both on the computer and on the phone. 

Can you be more specific please? What is not working? The [link above](https://zaboco.github.io/elm-draggable/basic.html) or locally? Also, what device and what browser?

For the second question: there is no need for ports and JS code. The subscriptions are from [`Browser.Events`](https://package.elm-lang.org/packages/elm/browser/1.0.1/Browser-Events) which uses native JS code:
https://github.com/zaboco/elm-draggable/blob/ecbb3bf3f8eccb2c8ae294a283d2dc607d80673a/src/Draggable.elm#L120-L122

**Comment by ta3pks** [comment]
@zaboco  hi i figured out the issue. I was trying to drag a video element around and the problem was the controllers as soon as i implemented custom controllers and drag the proper element everything started to work like a charm. Thanks for this amazing library
