### ISSUE TITLE
How to get the element where the drop happened

### ISSUE THREAD

**Issue by paul** [zaboco/elm-draggable#47]
It doesn't seem like its possible to know "where" the drop occurred (as a particular element), is that correct? I'm trying to implement a table with draggable rows (within the table to re-order, and into other tables on the page). I need to customize what the dragged object looks like, which this library allows, but the HTML5 Drag & Drop API does not. However, the HTML5 "ondrop" event provides a `target` which is the element that the mouse was over when the drop happened. I'm still fairly new to Elm, but it seems like the onDragEnd event provides no extra data at all, so the only thing I have to go by is the `position` stored in my model?

If this library doesn't provide that, what's the best way to get that? Subscribe to onMouseMove for the whole window?

**Comment by zaboco** [comment]
Yes, the current API does not provide a way to check the drop target. And it seems it's not straightforward to do that, even [in JavaScript](https://javascript.info/mouse-drag-and-drop), you have to use `document.elementFromPoint` while [setting `pointer-events: none`](https://stackoverflow.com/a/49174322/852300) on the drag target. Unfortunately, there is no way to get `document.elementFromPoint` in Elm (AFAIK).

But you can use [`Browser.Dom.getElement`](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#getElement) and check if the mouse position is inside the view of the drop target.

Hope this helps.
