### ISSUE TITLE
Implementing custom click effects on draggable elements

### ISSUE THREAD

**Issue by WaDelma** [zaboco/elm-draggable#51]
I am trying to add different actions for left, middle and right clicking an element that can also be dragged.
First I tried adding another handler for it using `elm-pointer-events`, but I realize that shouldn't work.
Next I tried to add `onClick` to `Draggable.customConfig`, but that seems to activate only for the left mouse button.

So I assume that something needs to be modified in the library to allow this.

**Comment by zaboco** [comment]
Hi! Have you tried using a [custom mouse trigger](https://github.com/zaboco/elm-draggable#custom-mouse-trigger)? 
That would store the `button` field on mouseDown, and then you could use that when handling the `onClick` message.

**Comment by WaDelma** [comment]
Yes, I am using it. The problem is that only left mouse button is handled so I don't get an event out of that.

**Comment by zaboco** [comment]
Ok, I see, I forgot about that. I'll take a look on the code (including your PR) these days and see if I can come up with something.

**Comment by zaboco** [comment]
Made the required changes, so now right and middle clicks are possible. Also added a RightClickExample.
Published as [5.0.0](https://package.elm-lang.org/packages/zaboco/elm-draggable/5.0.0/)
