### ISSUE TITLE
Expose absolute position of mouse when dragging

### ISSUE THREAD

**Issue by WaDelma** [zaboco/elm-draggable#52]
I had a trouble trying to add constraints such as restricting movement of elements to certain area and restricting elements to a grid.
I eventually overcame both by tracking the absolute position of the initial click with `Draggable.customMouseTrigger` and then summing up the drag deltas and using these recreated the absolute position of the cursor.

So it would be nice if the library itself exposed the position of the cursor instead of needing to recreate it.

**Comment by zaboco** [comment]
When designing the API of this lib, the focus was to make it as simple as possible for most common use cases, and add advanced options for custom behaviour. Such is the case with `customMouseTrigger`, it was introduced to solve exactly this need: being able to get the absolute position of the mouse.

If you end up using this logic in multiple places, you can of course extract it into some functions. Or even make a reusable lib with them.

I'll close this for now. Thanks
