### ISSUE TITLE
Allow manually trigger dragging

### ISSUE THREAD

**Issue by WaDelma** [zaboco/elm-draggable#53]
I want to be able to create an element with left mouse button and immediately start dragging it. I haven't been able to figure out how to do this with the library, but it seems that the library would need to add support for it.

Easiest and most flexible way to allow this that I can see is to allow triggering dragging manually.

**Comment by zaboco** [comment]
I guess that can be done similarly to the [free drawing example](https://github.com/zaboco/elm-draggable/blob/master/examples/FreeDrawingExample.elm).
I made a [basic example on ellie](https://ellie-app.com/bZryJJgd4T2a1), please tell me if that's what you had in mind.

**Comment by WaDelma** [comment]
Ah, of course that works :D 

Thanks a bunch!
