### ISSUE TITLE
Getting alt key when dragging

### ISSUE THREAD

**Issue by WaDelma** [zaboco/elm-draggable#55]
I want to change how dragging works depending on if alt is pressed or not. Right now I can use `customMouseTrigger` to get state of alt key at the start of dragging. However, this doesn't allow reacting to the changes in alt key while dragging.

I could listen keyboard events to and change some flag in the model to detect changes in alt key, but that doesn't feel great idea. As far as I can see if I could add custom decoder to `onMouseMove` that the library uses to create `onDragBy` messages this could be done in better way.

So I am wondering does it fit to the library to include this kind of mechanism? I guess the answer is negative, but I thought it would be worth asking.

**Comment by zaboco** [comment]
Hello. As you said, you could listen to key changes (with `Browser.Events.*` subscriptions) and store the state of the Alt key in the model. Why do you say that this is not ideal? I mean, storing the key state in the model is needed anyway, right? Could you try out an example on ellie-app.com and see if it works out? And we can discuss from there.

PS. Sorry if I come across as negativist or reluctant to any change. It's just that this library has been fairly stable for a long time, and it exposes custom hooks for more advanced use-cases. Bloating it with functionalities that can be resolved in the user-space would affect the existing users, especially if there are breaking changes. But even if there only new features, the API would become more complicated, so harder to understand. Hope it makes sense.

**Comment by WaDelma** [comment]
Hello. I have created rework of `elm-draggable`:s API and example that is using them: https://ellie-app.com/c7s9X7p9pDPa1

The example demonstrates how one can restrict dragged items to area by restricting maximum y, how one can restrict movement to grid when alt is not held and how one can change behavior of dragging to smooth drag when alt is held.

Notes:
- I changed it to not expose deltas but `DragInfo` that contains key pieces of information and helper functions that one can use that with
- I also added ability to decode the event messages everywhere
- I also changed how model of draggable and its user interact by adding setter and getter to config, not sure if this was a good idea
- Just realised that I don't restrict dragging to the main button, but I guess adding that isn't too hard.
- It is missing some callbacks and touch support
- Edit. Moving construction of message to config was a bad idea: One might need multiple message types

**Comment by zaboco** [comment]
Not sure that all of that is needed. Made [a similar example ](https://ellie-app.com/c8Zrq76xr6Ja1) using the current API. (Sure, it's not exactly the same, but it's the same idea). Please try to use the library as it is first, and only then try to change its API.

**Comment by WaDelma** [comment]
Well that example isn't really suitable: It doesn't actually remember the position. If you press/release alt it snap to grid even if not selected and so couldn't be extended to multiple draggables. But I guess it could be extended to that albeit inconveniently: You would need to track two different coordinates for each item (With only single selection you can get away with one extra position for the dragged item, but my use case also supports selecting multiple items and dragging them).

I guess I'll think about this. My first approach that used the library was super unclean, but most likely because I don't understand how the library is supposed to be used. It would be beneficial to include more complex examples.

**Comment by zaboco** [comment]
Yes, I know, it's not the same, the point is that the custom logic can be done. After all, the point of this lib is to track the mouse movement while dragging, and a few other stuff related to this. The app-specific logic should be done in the app. 

As for more complex examples, there is no plan in adding those, since the possibilities are endless. The examples showcase different use-cases, but only cover the starting-point. Of course, if you make a complex app that you can share, which proves some complex usages of the lib, I'll be happy to include a link to it in the README.

P.S. Might have seen that already, but there is a [MultipleTargetsExample](https://github.com/zaboco/elm-draggable/blob/master/examples/MultipleTargetsExample.elm) that might help. Of course, your use-case is more complicated than that, but a good starting point would be to track the positions of all items, as you said (and as it's done in this example).

**Comment by WaDelma** [comment]
Yes multi targets example is what I started with, but the main obstacle was how to constrain the dragging.

**Comment by WaDelma** [comment]
Also it felt really weird that I have to reconstruct the position of dragging to do anything more complex.
